# Generated by Django 6.0.5 on 2026-05-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('others', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='job_applications/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
