# Generated by Django 6.0.5 on 2026-06-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availablejobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('position', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('contact_period', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=300)),
                ('quantity', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male')),
                ('required_qualification', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='company',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='lot_no',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='others',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male'),
        ),
    ]
