# Generated by Django 6.0.5 on 2026-06-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availablejobs', '0002_jobdetail_remove_jobapplication_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='image',
            field=models.ImageField(default=1, upload_to='job_image/'),
            preserve_default=False,
        ),
    ]
