# Generated by Django 6.0.5 on 2026-06-02 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatecategory',
            name='tagline',
        ),
    ]
